/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./../components/App.vue')['default']
    Header: typeof import('./../components/Header.vue')['default']
    Page: typeof import('./../components/Page.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwitchDebug: typeof import('./../components/SwitchDebug.vue')['default']
  }
}
